# Generated by Django 5.2 on 2025-06-24 01:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cliente", "0001_initial"),
        ("tecnico", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Instalação", "Instalação"),
                            ("Manutenção", "Manutenção"),
                            ("Limpeza", "Limpeza"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Aceito", "Aceito"),
                            ("Em andamento", "Em andamento"),
                            ("Concluído", "Concluído"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Pendente",
                        max_length=20,
                    ),
                ),
                (
                    "data_solicitacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_execucao", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicos",
                        to="cliente.cliente",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="servicos",
                        to="tecnico.tecnico",
                    ),
                ),
            ],
        ),
    ]
