# Generated by Django 5.2 on 2025-06-24 01:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cliente", "0001_initial"),
        ("tecnico", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avaliador_tipo",
                    models.CharField(
                        choices=[("cliente", "Cliente"), ("tecnico", "Técnico")],
                        max_length=10,
                    ),
                ),
                ("nota", models.PositiveSmallIntegerField()),
                ("comentario", models.TextField(blank=True)),
                (
                    "data_avaliacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_recebidas",
                        to="cliente.cliente",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_recebidas",
                        to="tecnico.tecnico",
                    ),
                ),
            ],
        ),
    ]
