# Generated by Django 5.2 on 2025-06-24 01:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cliente", "0001_initial"),
        ("servico", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("pix", "PIX"),
                            ("cartao_credito", "Cartão de Crédito"),
                            ("cartao_debito", "Cartão de Débito"),
                            ("boleto", "Boleto"),
                            ("dinheiro", "Dinheiro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("recusado", "Recusado"),
                            ("estornado", "Estornado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "comprovante",
                    models.ImageField(blank=True, null=True, upload_to="comprovantes/"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamentos",
                        to="cliente.cliente",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamentos",
                        to="servico.servico",
                    ),
                ),
            ],
        ),
    ]
