# Generated by Django 5.2 on 2025-06-24 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tecnico", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TecnicoEspecialidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_especialidade", models.CharField(max_length=100)),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="especialidades",
                        to="tecnico.tecnico",
                    ),
                ),
            ],
            options={
                "unique_together": {("tecnico", "nome_especialidade")},
            },
        ),
    ]
